language: nix
before_install:
  - nix-channel --add https://nixos.org/channels/nixos-18.09 nixpkgs
  - nix-channel --update

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: $GITHUB_REPO
  local_dir: result
  on:
    branch: master
